version: '3.9'

services:
  web:
    container_name: web
    # image: apptemplate.azurecr.io/react
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 3000:${REACT_APP}
    environment:
      - REACT_APP=${REACT_APP}
    command: wait-for postgres:5432 -t 40 -- ./start.sh
    volumes:
      - ./web:/home/node/app
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: wait-for postgres:5432 -t 40 -- ./start.sh
    ports:
      - $API_PORT:${API_PORT}
    environment:
      - API_PORT=${API_PORT}
    volumes:
      - ./backend:/home/node/app
    links:
      - "postgres:pgsql-server"
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    # hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  shared-network:


volumes:
  postgres-data:
  pgadmin-data:
